### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by LinasKo** [Kbdgwniai/fintech#1]
- [x] Display list of items as a QR code.
- [x] Read the QR code.
- [x] Store the data in a database.
- [ ] Obtain the data using NFC.
- [x] ~~Find, maximum length of QR and NFC line.~~ More than enough.
     QR: We've used up about 5% of the space for check with 5 items. Maximum seems to be around 4000 characters.
     NFC: 1kB is realistic, as stated here http://stackoverflow.com/questions/9691863/how-many-characters-can-be-sent-at-a-time-with-nfc-messages
- [ ] Display both the bank transaction and the Receipt Entry databases.
- [ ] Add the option to display the Tax exemptions upon checking items.
- [ ] Add the option to export as pfd or xlr or csv or json

**Comment by Kbdgwniai** [comment]
Pattern p = Pattern.compile("(.*) (\d+)x(\d+\.\d\d) (\d+\.\d\d)"); 
        Matcher product = p.matcher(testdata);
        //Matcher quantity;
        //Matcher price;

```
    while (product.find())
    {
        for(int i = 1; i<=4; i++)
        {
            System.out.println(product.group(i));
        }

    }
```

**Comment by Kbdgwniai** [comment]
ID00000001 Sainsburys
Chicken 2.000x3.50 7.00
Turkey 3.000x2.50 7.50
cucumber 1.000x0.69 0.69
organic watermelon 1.000x3.50 3.50
toilet paper 2.000x3.50 7.00
pen 1.000x0.20 0.20
notepad 2.000x2.20 4.40
Organic Casserole Beef 3.000x3.50 10.50
